#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: web-management
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置驼峰命名
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#配置阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: tujavaweb-ai
    region: cn-beijing