##数据源配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tlias
#    username: root
#    password: root
##mybatis配置
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#
#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: springboot-aop-quickstart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置驼峰命名
    map-underscore-to-camel-case: true







